config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :search, only: [:index, :show]

  root to: "medical_app#home"
  # match '/search',  to: 'medical_app#search', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_region.rb
class BodyRegion < ApplicationRecord
  # has_many :symptom, class_name:"body_region", foreign_key: "symptom_id"
  has_many :symptoms
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :children,
  #           class_name: "Category",
  #           foreign_key: "parent_id"
end

app/models/point.rb
class Point < ApplicationRecord
  has_many :category, foreign_key: "category_id"
  has_many :symptom, foreign_key: "symptom_id"
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  def self.body_region_id
    where(body_region_id: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/medical_app_controller.rb
class MedicalAppController < ApplicationController
  def home
  end

  # def symptoms
  #   unless params[:body_region_id].blank?
  #     body_region_id = params[:body_region_id]
  #   end
  # end

  def search
    @categories = Category.all
    @body_regions = BodyRegion.all
    @symptoms = Symptom.all
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @body_regions = BodyRegion.all
    @symptoms = Symptom.all
    @symptom = Symptom.body_region_id
    # respond_to do |format|
    #   format.html # html形式でアクセスがあった場合は特に何もなし(@messages = Message.allして終わり）
    #   format.json { @new_message = Symptom.where('id > ?', params[:symptoms][:id]) } # json形式でアクセスがあった場合は、params[:message][:id]よりも大きいidがないかMessageから検索して、@new_messageに代入する
    # end
  end

  def show
    @body_regions = BodyRegion.all
    @body_region = BodyRegion.find(params[:id])
    @symptoms = Symptom.all
    @symptom = Symptom.body_region_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medical_app_helper.rb
module MedicalAppHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<header>
<ul class="nav justify-content-end content-area">
  <a class="tag">HOSPITAL SEARCH</a>
  <li class="nav-item nav-link active"><%= link_to "HOME", root_path %></li>
  <li class="nav-item nav-link"><%= link_to "SEARCH", search_index_path %></li>
  <li class="nav-item nav-link disabled"><%= link_to "DASHBOARD", rails_admin_path %></li>
</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>HOSPITAL SEARCH | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'symptom' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/medical_app/home.html.erb
<% provide(:title, 'HOME') %>

<div class="content content-area content-background">
  <p class="content-text">- How to use -</p>
</div>

<div class="content content-area content-background">
  <p class="content-text">- Infomation -</p>
</div>

app/views/medical_app/search.html.erb
<% provide(:title, 'Search') %>
  <style>
    /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
    #map {
      height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    body,
    html {
      height: 100%;
      margin:: 0;
      padding: 0;
    }
  </style>

<%= render 'medical_app/symptom' %>

<div class="content content-area content-background">
  <p class="content-text">- List -</p>
</div>

<div id="map"></div>

<%= javascript_include_tag 'google_map_api' %>

<script async="async" defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJhrrQZ2JozeUYwTF3h4BhNZQPCiHovG4&callback=initMap"></script>

app/views/search/_search_index.html.erb
<% provide(:title, 'Search') %>
  <style>
    /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
    #map {
      height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    body,
    html {
      height: 100%;
      margin:: 0;
      padding: 0;
    }
  </style>

<%= render 'search/symptom' %>

<div class="content content-area content-background">
  <p class="content-text">  - List - </p>
</div>

<div id="map"></div>

<%= javascript_include_tag 'google_map_api' %>

<script async="async" defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJhrrQZ2JozeUYwTF3h4BhNZQPCiHovG4&callback=initMap"></script>

app/views/search/_symptom.html.erb
<section>
<div class="content content-area content-text content-background">
  <p class="content-text"> - Symptom - </p>
    <div class="body-region">
      <h2>【 身体部位 】</h2>
      <div id="body-region-position">
        <% @body_regions.each.with_index(1) do |set, i| %>
            <%= link_to set.name, search_path(set.id), class: 'list-group-item list-group-item-action list-group-item-primary', id: 'body-region-list' %>
            <!-- <button class='list-group-item list-group-item-action list-group-item-primary button1' id='body-region-list'><%= set.name %>#</button> -->
        <% end %>
      </div>
    </div>

  <div class="symptom">
    <h2>【 症状 】</h2>
    <p id="result"></p>
    <div class="symptom-list">
      <% if current_page?(search_index_path) %>
        <% @symptom.where(:body_region_id => @body_regions).find_each do |set| %>
          <tr>
            <td>
              <%= check_box_tag :symptom %>
              <%= label_tag :symptom, set.name %>
            </td>
          </br>
          </tr>
        <% end %>
      <% else %>
        <% @symptoms.where(:body_region_id => @body_region).find_each do |set| %>
          <tr>
            <td>
              <%= check_box_tag :symptom %>
              <%= label_tag :symptom, set.name %>
            </td>
          </br>
          </tr>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/search/index.html.erb
<% provide(:title) %>
<%= render 'search/search_index' %>

app/views/search/sample.html.erb
<p>js_sample</p>

app/views/search/show.html.erb
<%= render 'search/search_index' %>